### PR TITLE
fix: fix css flex/height issues in safari

### LINKED ISSUE #238: Safari doesn't use full screen space
## Bug Report 🐛

Safari doesn't use the full screen real estate.

Safari 
Screen Shot 2020-07-03 at 4 30 36 PM

Chrome
Screen Shot 2020-07-03 at 4 40 03 PM

## To Reproduce ✔️

Open testing-playground.com in Safari.

## Expected behavior 🤔
Safari to look the same as Chrome and use the full screen. 

## Suggested solution 🔦
Seems to be a css issue with safari. Haven't quite narrowed down exactly where it's displaying incorrectly. 

## Your Environment 💻

- _browser_: Safari
- _os_: Mac 10.15.5

### PR DESCRIPTION
**Pull request by bmeverett**
**What**:
Fix #238 

**Why**:
To improve how the site looks and behaves in Safari to make it align with Chrome. 

**How**:
Update css classes to work on Safari. I'm not the best at css, but I removed/added some classes to make Safari show more like Chrome. I checked Chrome while making these changes as well and it didn't seem to be affected. Happy to look at a different/better way of doing things, or if there was something I missed 

**Safari**
Screen Shot 2020-07-06 at 8 44 36 AM

**Chrome**
Screen Shot 2020-07-06 at 8 44 40 AM

**Checklist**:

- [ ] Tests n/a
- [x] Ready to be merged

### CODE REVIEW

File: src/components/Preview.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ function Preview({ markup, variant, forwardedRef, dispatch }) {
           ref={refSetter}
           src="/sandbox.html"
           security="restricted"
-          className="w-full h-full"
+          className="absolute w-full h-full"
```
Comment (smeijer) [inline src/components/Preview.js:91]: I think that instead of adding an `absolute` position here, which would break the element flow, we can remove the wrapping `<div className="flex-auto relative">`, as it doesn't do anything anymore. And only apply the `className="flex-auto"` to the `iframe`. So no `absolute`, `w-full` or `h-full`.

**Comment by bmeverett** [comment]
Thanks @smeijer! I've applied the fixes you requested. Thanks for tidying that up.

**Comment by smeijer** [comment]
@all-contributors please add @bmeverett for code
